# Generated by Django 2.1.2 on 2018-11-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'pages'},
        ),
    ]
