# Generated by Django 2.1.2 on 2018-11-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181102_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pages',
        ),
        migrations.AddField(
            model_name='player',
            name='AB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='AVG',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='BB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='CS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='HR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='K',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='OBP',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='RBI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='SB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='SLG',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='X2B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='X3B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Year',
            field=models.IntegerField(default=0),
        ),
    ]
