# Generated by Django 2.1.2 on 2018-11-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181102_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
