# Generated by Django 2.1.2 on 2018-11-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='Position',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='Year',
            field=models.CharField(default='Sr.', max_length=20),
        ),
    ]
