# Generated by Django 2.1.2 on 2018-11-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20181103_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
