# Generated by Django 2.1.2 on 2018-11-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='jonson',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
