# Generated by Django 2.1.2 on 2018-11-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_team_jonson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='jonson',
        ),
    ]
