# Generated by Django 2.1.2 on 2018-11-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_team_jonson'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='urlname',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
