# Generated by Django 2.1.2 on 2018-11-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_player_urlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='AB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='AVG',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='team',
            name='BB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='CS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='HR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='K',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='OBP',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='team',
            name='RBI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='SB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='SLG',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='team',
            name='X2B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='X3B',
            field=models.IntegerField(default=0),
        ),
    ]
