# Generated by Django 2.1.2 on 2018-11-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20181104_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='OPS',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
