# Generated by Django 2.1.2 on 2018-11-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20181104_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(default='', max_length=50)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Year', models.CharField(default='Sr.', max_length=20)),
                ('APP', models.IntegerField(default=0)),
                ('GS', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('W', models.IntegerField(default=0)),
                ('SV', models.IntegerField(default=0)),
                ('CG', models.IntegerField(default=0)),
                ('IP', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('H', models.IntegerField(default=0)),
                ('ER', models.IntegerField(default=0)),
                ('BB', models.IntegerField(default=0)),
                ('K', models.IntegerField(default=0)),
                ('K_9', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('HR', models.IntegerField(default=0)),
                ('ERA', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Team')),
            ],
        ),
    ]
