# Generated by Django 2.1.2 on 2018-11-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_pitcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=50)),
                ('Velocity', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('Pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pitcher')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='BB_P',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='CG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ER',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ERA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='team',
            name='HR_P',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='H_P',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='IP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='K_9_P',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='team',
            name='K_P',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='SV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='W',
            field=models.IntegerField(default=0),
        ),
    ]
