# Generated by Django 2.1.2 on 2018-11-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20181104_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='CG',
        ),
        migrations.RemoveField(
            model_name='team',
            name='H_P',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SV',
        ),
    ]
