# Generated by Django 2.1.2 on 2018-11-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20181104_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='H_P',
            field=models.IntegerField(default=0),
        ),
    ]
