# Generated by Django 2.1.2 on 2018-11-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_team_h_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='IP',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
