# Generated by Django 2.1.2 on 2018-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20181104_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='Hand',
            field=models.CharField(default='R', max_length=5),
        ),
    ]
