# Generated by Django 2.1.2 on 2018-11-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_pitcher_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcher',
            name='K_9',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
