# Generated by Django 2.1.2 on 2018-11-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20181105_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='APP',
        ),
    ]
