# Generated by Django 2.1.2 on 2018-11-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_team_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcher',
            name='ERA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='ERA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
