# Generated by Django 2.1.2 on 2018-11-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20181105_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcher',
            name='IP',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
