# Generated by Django 2.1.2 on 2018-11-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20181107_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pitches',
            new_name='Pitch',
        ),
    ]
