# Generated by Django 2.1.2 on 2018-11-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20181108_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name_plural': 'pitches'},
        ),
    ]
