# Generated by Django 2.1.2 on 2018-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20181108_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='Order',
            field=models.IntegerField(default=0),
        ),
    ]
