# Generated by Django 2.1.2 on 2018-11-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_pitch_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='Scouting_Report',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
