# Generated by Django 2.1.2 on 2018-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_pitcher_scouting_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Video',
            field=models.BooleanField(default=False),
        ),
    ]
