# Generated by Django 2.1.2 on 2018-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_player_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Scouting_Report',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='Scouting_Report',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
