# Generated by Django 2.1.2 on 2018-11-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20181111_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcher',
            name='Scouting_Report',
            field=models.CharField(default='None available.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='player',
            name='Scouting_Report',
            field=models.CharField(default='None available.', max_length=5000),
        ),
    ]
