# Generated by Django 2.1.2 on 2018-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20181111_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='Video',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='Video',
            field=models.CharField(default='', max_length=50),
        ),
    ]
