# Generated by Django 2.1.2 on 2018-11-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20181123_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='Video',
            field=models.BooleanField(default=False),
        ),
    ]
