# Generated by Django 2.1.2 on 2019-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20181123_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='K_9_P',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
